on: push
name: Frontend test
jobs:
  test:
    name: test front
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    default:
      run:
        working-directory: front
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm front:install
        run: npm run install
        env:
          CI: true
      - name: npm front:test
        run: npm run test
        env:
          CI: true